name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install -U pip 'django==3.2.16'
        

        
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
    
          SCRIPT_BEFORE: |
            whoami
            ls -al
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements.txt
            yes | ./downloadNashSolver.sh
            ./start_app.sh
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
          
    - name: Run Tests
      run: |
        python manage.py test
